config/routes.rb
Rails.application.routes.draw do
  
  root 'flights#index'

  resources :flights, only: [:index, :show]
  resources :bookings, only: [:new, :create, :show]

end

app/models/airport.rb
class Airport < ActiveRecord::Base
	has_many :departures, :foreign_key => :start_location, :class_name => "Flight"
	has_many :arrivals, :foreign_key => :end_location, :class_name => "Flight"
end

app/models/booking.rb
class Booking < ActiveRecord::Base
	belongs_to :flight
	has_many :tickets
	has_many :passengers, through: :tickets
	accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ActiveRecord::Base
	belongs_to :from_airport, :foreign_key => :start_location, :class_name => "Airport"
	belongs_to :to_airport, :foreign_key => :end_location, :class_name => "Airport"
	has_many :bookings

	def self.search(params)
		@message = ""
		if params[:search]
			format_date = date_format(params[:chosen_date])
			Flight.where("start_location = ? AND end_location = ? AND start_time LIKE ?", params[:from], params[:to], "%#{format_date}%")
		else
			Flight.none
		end
	end

	def self.date_format(date)
		year = date[6..9]
		month = date[0..1]
		day = date[3..4]
		return "#{year}-#{month}-#{day}"
	end
end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
	has_many :tickets
	has_many :bookings, through: :tickets
	has_many :flights, through: :bookings
	
	validates :name, presence: true
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
	validates :email, 
	           presence: true, 
	           length: { maximum: 255 },
	           format: { with: VALID_EMAIL_REGEX }
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
	belongs_to :booking
	belongs_to :passenger
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

	def new
		@flight = Flight.find(params[:flight_id])
		@booking = Booking.new
		params[:passengers].to_i.times { @booking.passengers.build }
	end

	def create
		@booking = Booking.new(booking_params)
		if @booking.save
			PassengerMailer.thank_you_email(@booking).deliver
			flash[:success] = "Flight has been booked"
			redirect_to @booking
		else
			@flight = Flight.find(params[:flight_id])
			flash.now[:error] = "Make sure all info is entered for all passengers"
			render :new
		end
	end

	def show
		@booking = Booking.find(params[:id])
	end

	private

		def booking_params
			params.require(:booking).permit(:flight_id, passengers_attributes: [:id, :name, :email])
		end
# end private
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController

	def index
		@airports = Airport.all.map { |a| [a.name, a.id] }
		@dates = Flight.all.order(:start_time)
		@dates = @dates.map { |d| d.start_time.strftime("%m/%d/%Y") }
		@dates.uniq!
		@flights = Flight.all
		@chosen_from = params[:from]
		@chosen_to = params[:to]
		@chosen_pass = params[:passenger_count]
		@chosen_date = params[:chosen_date]
		@message = ""
		if @chosen_from == "" || @chosen_to == ""
			@message = "Please chose two airports"
		elsif @chosen_from == @chosen_to
			@message = "Please choose two different airports"
		end
		if @message == "" && @chosen_pass == ""
			@message = "Please choose number of passengers"
		end
		if @message == "" && @chosen_date == ""
			@message = "Please chose a date to fly"
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis
  def full_title(page_title = "")
    base_title = "Flight Booker"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<%= form_for(@booking) do |f| %>
	<%= f.hidden_field :flight_id, value: params[:flight_id] %>
	<%= hidden_field_tag(:flight_id, params[:flight_id]) %>
	<h2>Book Flight
		<span>Enter Passenger Info</span>
	</h2>
	<p>
		<strong>Flight #:</strong> <%= @flight.id %><br/>
		<strong>From:</strong> <%= @flight.start_location %><br/>
		<strong>To:</strong> <%= @flight.end_location %><br/>
		<strong>Date:</strong> <%= @flight.start_time.strftime("%a %b %d, %Y") %><br/>
		<strong>Time:</strong> <%= @flight.start_time.strftime("%I:%M %p") %>
	</p>
	<hr/>
	<% p_count = 1 %>
	<%= f.fields_for :passengers do |p| %>
		<strong>Passenger <%= p_count %>:</strong><br/>
		<%= p.label :name, "Name:" %>
		<%= p.text_field :name %>

		<%= p.label :email, "Email:" %>
		<%= p.email_field :email %>
		<% p_count += 1 %>
		<br/><br/>
	<% end %>
	<div class="submit">
		<%= f.submit "Book Flight" %>
	</div>
<% end %>

app/views/bookings/show.html.erb
<form>
	<h2>Flight Confirmation:</h2>
	<p>
		<strong>Flight #:</strong> <%= @booking.flight_id %><br/>
		<strong>From:</strong> <%= @booking.flight.start_location %><br/>
		<strong>To:</strong> <%= @booking.flight.end_location %><br/>
		<strong>Date:</strong> <%= @booking.flight.start_time.strftime("%a %b %d, %Y") %><br/>
		<strong>Time:</strong> <%= @booking.flight.start_time.strftime("%I:%M %p") %>
	</p>
	<hr/>
	<% @booking.passengers.each_with_index do |p, i| %>
		<p>
			<strong>Passenger <%= i + 1 %>:</strong><br/>
			<strong>Name:</strong> <%= p.name %><br/>
			<strong>Email:</strong> <%= p.email %><br/>
		</p>
	<% end %>
</form>

app/views/flights/index.html.erb
<%= form_tag(flights_path, method: :get) do %>
	<%= hidden_field_tag :search %>
	<h2>Search Flights</h2>
	
	<%= select_tag(:from, options_for_select(@airports, @chosen_from), prompt: "From") %>

	<%= select_tag(:to, options_for_select(@airports, @chosen_to), prompt: "To") %>

	<%= select_tag(:passenger_count, options_for_select([1,2,3,4], @chosen_pass), prompt: "Passengers") %>

	<%= select_tag(:chosen_date, options_for_select(@dates, @chosen_date), prompt: "Date") %>

	<div class="submit">
		<%= submit_tag("Find Flights") %>
	</div>

	<% if params[:search] && @message != ""%>
		<br/><%= @message %>
		<% @message = "" %>
	<% end %>
<% end %>
<% if !@flights.none? && @message == ""%>
	<%= form_tag new_booking_path,  method: :get do %>
		<%= hidden_field_tag :passengers, params[:passenger_count] %>
		<h2>Pick a flight</h2>
		<table>
			<thead>
				<tr>
					<th width = "40"></th>
					<th width = "50">Flight</th>
					<th width = "150">Date</th>
					<th width = "85">Time</th>
					<th width = "50">From</th>
					<th width = "50">To</th>
					<th width = "90">Duration</th>
				</tr>
			</thead>
			<tbody>
				<% @flights.each do |flight| %>
					<tr>
						<td><%= radio_button_tag :flight_id, flight.id %></td>
						<td><%= flight.id %></td>
						<td><%= flight.start_time.strftime("%a %m/%d/%y") %></td>
						<td><%= flight.start_time.strftime("%I:%M %p") %></td>
						<td><%= flight.start_location %></td>
						<td><%= flight.end_location %></td>
						<td><%= flight.duration/60 %> hours</td>
					</tr>
				<% end %>
			</tbody>
		</table>
		<div class="submit">
			<%= submit_tag("Select Flight") %>
		</div>
	<% end %>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <ul>
  	<li>flight booker</li>
    <li>made by Talha Ijaz Shamsi</li>
  </ul>
</footer>

app/views/layouts/_header.html.erb
<header>
  <h1><%= link_to "Flight Booker", root_url %></h1>
</header>

app/views/layouts/_shim.html.erb
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta charset="utf-8" >
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
    <%= javascript_importmap_tags %>
</head>
<body>
  <div id="wrapper">
    <%= render 'layouts/header' %>
    <% flash.each do |message_type, message| %>
      <div class = "alert alert-<%= message_type %>">
        <%= message %>
      </div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div> <!-- wrapper -->
</body>
</html>